ARG RUBY_VERSION=3.0.2

FROM ruby:${RUBY_VERSION}-alpine as build

RUN apk add \
  --no-cache \
  build-base git postgresql-dev curl tzdata less bash nodejs openssl

RUN mkdir -p /usr/src/build \
  && addgroup -S www \
  && adduser -G www -S www \
  && chown www:www /usr/src/build
USER www

WORKDIR /usr/src/build
